name: Setup gh-pages branch

on:
  workflow_dispatch:
    inputs:
      default_commit_message:
        description: "Initial gh-pages commit message"
        required: false
        default: "chore(ci): initialize gh-pages branch for benchmark history"

permissions:
  contents: write

jobs:
  bootstrap:
    name: Bootstrap gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare site content
        run: |
          mkdir -p _ghpages/benchmark-data
          cat > _ghpages/benchmark-data/index.html << 'EOF'
          <!doctype html>
          <html lang="en">
          <head>
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <title>Benchmark Data Directory</title>
            <style>
              body{font:16px/1.5 -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif;margin:2rem;}
              a{color:#0366d6;text-decoration:none}
              a:hover{text-decoration:underline}
              .note{color:#555}
            </style>
          </head>
          <body>
            <h1>Benchmark Data</h1>
            <p class="note">This directory will be populated automatically by CI runs on the <code>main</code> branch via <code>github-action-benchmark</code>.</p>
            <p>Return to the <a href="../">dashboard</a>.</p>
          </body>
          </html>
          EOF
          cat > _ghpages/README.md << 'EOF'
          # Benchmark Data

          This branch stores benchmark history for github-action-benchmark.

          - Raw data: `benchmark-data/`
          - Dashboard: `index.html`
          EOF
          cat > _ghpages/index.html << 'EOF'
          <!doctype html>
          <html lang="en">
          <head>
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <title>metrics-lib Benchmark Dashboard</title>
            <style>
              body{font:16px/1.5 -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif;margin:2rem;}
              h1{font-size:1.6rem;margin-bottom:0.5rem}
              .note{color:#555}
              ul{line-height:1.8}
              code{background:#f6f8fa;padding:2px 4px;border-radius:4px}
              a{color:#0366d6;text-decoration:none}
              a:hover{text-decoration:underline}
            </style>
          </head>
          <body>
            <h1>metrics-lib Benchmark Dashboard</h1>
            <p class="note">This page hosts benchmark history produced by <code>github-action-benchmark</code>.</p>
            <ul>
              <li>Raw data directory: <a href="./benchmark-data/">benchmark-data/</a></li>
              <li>Project README: <a href="https://github.com/jamesgober/metrics-lib#benchmarks">Benchmarks section</a></li>
              <li>Docs: <a href="https://github.com/jamesgober/metrics-lib/blob/main/docs/benchmarks/README.md">docs/benchmarks/README.md</a></li>
            </ul>
            <p class="note">Tip: After a few CI runs on <code>main</code>, you will see data accumulate under <code>benchmark-data/</code>. We can enhance this dashboard later to visualize trends.</p>
          </body>
          </html>
          EOF
          touch _ghpages/.nojekyll

      - name: Publish to gh-pages (force orphan)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _ghpages
          publish_branch: gh-pages
          force_orphan: true
          enable_jekyll: false
          commit_message: ${{ inputs.default_commit_message }}
